/* ==========================================================================
   data.js — 이 파일만 고치면 사이트 내용이 바뀝니다.
   카드 추가: 원하는 섹션의 cards 배열에 객체 하나 추가.
   --------------------------------------------------------------------------
   card = {
     title:   "카드 제목",            // 필수
     desc:    "한 줄 설명",           // 선택 · 한 문장 90자 이내 (아래 ★★)
     url:     "https://... 또는 docs/xxx.html",  // 필수 (없으면 "#")
     status:  "Live" | "진행중" | "완료" | "초안",
     version: "v4.3",
     updated: "2026-08-07 10:48",     // 날짜 + 시각(HH:MM)
     pinned:  true,                  // 상단 강조
     tags:    ["태그", "태그"],        // 최대 3개
     project: "smg",                 // 선택 · 아래 PROJECTS 의 키. 카드 테두리색 + 제목줄 칩.
                                     //   생략하면 종전대로 섹션 accent 로 그려진다.
     share:   false,                 // 선택 · 설정탭 전용. 없으면 노출, false 면 허브에서 숨김
   }
   --------------------------------------------------------------------------
   ★★ 허브는 "무슨 문서가 있나"를 훑는 인덱스다. desc 는 문서를 열 이유 하나만
     한 문장으로 적는다. 수치 나열 · 버전 변경이력("v5.3 정정", "08-19 갱신 —")은
     허브가 아니라 문서 본문에 쓴다. 카드 desc 에는 CSS 2줄 클램프가 걸려 있어
     길게 써도 잘려 보이기만 한다. 태그는 최대 3개 — 지금 태그는 필터가 아니라
     라벨이므로 많아질수록 스캔만 방해한다.
     --------------------------------------------------------------------------
   ★★★ 태그 축은 3개다 — **근거 / 주제 / 성격**. 축마다 최대 1개씩, 카드당 3개 이하.
     근거 = 코드 실측 · BigQuery · 프리팹 실측 · 커밋 히스토리
     주제 = 토너먼트 · 공유 · 초대 · 광고 · 온보딩 · 로딩 · 컨텍스트 · 로그 · 아트 · 데코 · 머지 · 인프라 · 정산 · 네트워크 오류 · FB 플랫폼
     성격 = 상시 · 정본 · 임시 · 이식 · 인터랙티브 · 레퍼런스 · 역기획 · 착수 점검
     (주간 KPI 계열만 3축 · 축1 · 축2 · 축3 을 따로 쓴다)
     **섹션 라벨과 프로젝트 칩이 이미 말하는 것은 태그로 적지 않는다.**
     그래서 "QA" · "전후비교" · "레퍼런스"(다이어그램) · "스토리머지" · "4프로젝트" 같은
     태그를 뺐다. 대신 app.js 의 검색 색인에 섹션 라벨을 넣어 검색은 그대로 잡히게 했다.
   --------------------------------------------------------------------------
   ★ 카드를 추가·수정했으면 아래 SITE.updated 와 index.html 의
     <script src="data.js?v=YYYYMMDDHHMM"> 를 **같은 시각으로** 함께 고칠 것.
     이걸 빼먹으면 브라우저 캐시 때문에 새 카드가 최대 10분간 안 보입니다.
   ========================================================================== */

const SITE = {
  title: "Supergene 기획 허브",
  subtitle: "팀이 함께 보는 기획 · 수치 · 검증 문서 인덱스",
  updated: "2026-09-02 18:39",
};

/* --------------------------------------------------------------------------
   PROJECTS — 카드의 project 키를 이름·식별색으로 푼다.
   허브 카드의 왼쪽 테두리와 제목줄 칩이 이 색을 쓴다. 섹션(분석·검증·QA·배포)은
   제목과 nav pill 로 이미 구분되므로, 카드 테두리는 프로젝트 쪽에 양보한다.
   project 를 안 적은 카드는 종전대로 섹션 accent 로 그려진다(무손상).
   색 토큰은 style.css 의 프로젝트 식별색과 같은 값이다.
   -------------------------------------------------------------------------- */

const PROJECTS = {
  smg: { name: "스토리머지", token: "--smg" },
  cmt: { name: "코인매치", token: "--cmt" },
  sol: { name: "솔리테어", token: "--sol" },
  coz: { name: "코지", token: "--coz" },
  mah: { name: "마종", token: "--mah" },
  pbm: { name: "퍼블마", token: "--pbm" },
  bbl: { name: "블록블라스트", token: "--bbl" },
  tpz: { name: "더퍼즐", token: "--tpz" },
  // 여러 프로젝트를 나란히 놓고 대조하는 문서. 한 색을 고를 수 없으니 무채색으로 둔다.
  multi: { name: "다중대조", token: "--text-dim" },
};

const SECTIONS = [
  {
    id: "analysis",
    label: "분석",
    accent: "analysis",
    desc: "라이브 데이터 · 코드베이스 실측 분석",
    cards: [
      {
        title: "솔리테어 483 전후 — 벤치 대조",
        desc: "같은 3일 창을 client_version으로 갈라 482 이하와 483을 DAU당 10행으로 대조한다. 483에도 초대가 살아 있어 A/B는 아직 시작 전이다.",
        url: "docs/sol-era-watch.html",
        project: "sol",
        status: "초안",
        version: "v2.1",
        updated: "2026-09-02 18:39",
        pinned: false,
        tags: ["BigQuery", "공유", "이식"],
      },
      {
        title: "머지 피드백 연출집",
        desc: "연출 14종의 시간·이징·세기를 표에서 직접 고치면 옆 무대가 그 값으로 논다. 병합은 4×4 샌드박스라 칩이 계속 차오르고, 창고에서 보드로 올리고, 문구는 누른 칩 위로 떠오른다. [설정 복사] 로 붙여넣기 가능한 cc.tween 상수를 그대로 가져간다.",
        url: "docs/merge-feedback-anim.html",
        project: "smg",
        status: "초안",
        version: "v3.7",
        updated: "2026-09-01 16:04",
        pinned: false,
        tags: ["연출", "튜닝 도구", "인터랙티브"],
      },
      {
        title: "아이소메트릭 데코 영역 — 등장 연출 · 레이어",
        desc: "빈 데코 영역에서 미션을 눌러 오브젝트를 하나씩 등장시켜 본다. 보간 1초는 root 하나의 연출 시간이고 그 안에서 스프라이트가 조립되듯 들어온다 — 맞춘 값이 그대로 Cocos 코드로 나온다.",
        url: "docs/deco-tween-iso.html",
        status: "완료",
        version: "v3.11",
        updated: "2026-09-01 17:18",
        pinned: false,
        project: "smg",
        tags: ["데코", "인터랙티브"],
      },
      {
        title: "채팅 캐릭터 애니메이션 용량 계산기",
        desc: "캐릭터와 감정이 늘면 용량이 어디까지 가나. 프레임 시퀀스 · 노드 트랜스폼 · Spine 세 방식을 같은 조건에 놓고 계산한다.",
        url: "docs/chat-anim-size-calc.html",
        status: "완료",
        version: "v1.8",
        updated: "2026-09-01 10:31",
        pinned: false,
        project: "smg",
        tags: ["코드 실측", "아트", "인터랙티브"],
      },
      {
        title: "게임 장르별 AWS 아키텍처 — 2024",
        desc: "메가존이 준 설명 없는 구성도 4장을 다시 그렸다. 장르 차이는 결국 \"게임 서버가 상태를 갖느냐\" 한 축에서 갈린다.",
        url: "docs/game-genre-aws-architecture.html",
        status: "완료",
        version: "v1.0",
        updated: "2026-08-27 17:13",
        pinned: false,
        tags: ["인프라", "레퍼런스"],
      },
      {
        title: "스토리 머지 — 로그 적용 매트릭스",
        desc: "주요 게임 5개 로그를 전량 실측해 프로토에 넣을 수 있는 것만 골랐다. 호출문이 이미 심긴 18계열과 새로 넣을 16계열을 갈랐고, 공통 로그 등록·호출 규약을 붙였다.",
        url: "docs/story-merge-log-matrix.html",
        project: "smg",
        status: "완료",
        version: "v2.1",
        updated: "2026-08-28 12:05",
        pinned: false,
        tags: ["로그", "코드 실측"],
      },
      {
        title: "FB 게이밍 탭 복귀 지면 — 노출 조사 히스토리",
        desc: "포스트는 그 지면에 자동으로 실린다. 문제는 이틀간 발사가 2건뿐이라는 것. 게이트 6개가 무로그로 막고 있다.",
        url: "docs/fb-exit-surface-investigation.html",
        project: "multi",
        status: "진행중",
        version: "v2.0",
        updated: "2026-08-26 09:56",
        pinned: false,
        tags: ["FB 플랫폼", "공유", "코드 실측"],
        share: false,
      },
      {
        title: "광고 유입 NRU 첫터치 — 원인 규명",
        desc: "업데이트·빌드·클라 결함 전부 배제. 같은 조건 대조군이 45.9%·70.7%인데 광고만 7.3%. 남은 원인은 유입 의도.",
        url: "docs/ua-ad-nru-first-touch.html",
        project: "multi",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-20 18:52",
        pinned: false,
        tags: ["광고", "온보딩", "BigQuery"],
        share: false,
      },
      {
        title: "주간 KPI 3축 — 분석 입구",
        desc: "광고 노출 · 플레이 횟수 · 공유 3축을 전주 대비 숫자로만 본다. 매주 갱신되는 분석 입구.",
        url: "docs/weekly-kpi.html",
        project: "sol",
        status: "Live",
        version: "v3.5",
        updated: "2026-08-24 14:00",
        pinned: true,
        tags: ["3축", "BigQuery", "상시"],
        share: false,
      },
      {
        title: "공유 · 메시지 — 왜 실패하나",
        desc: "피드공유 실패의 81%가 유저 취소가 아니라 호출 충돌. 겹치는 호출 후보는 4개까지 좁혀졌다.",
        url: "docs/viral-surface-cross-project.html",
        project: "multi",
        status: "진행중",
        version: "v5.2",
        updated: "2026-08-19 08:55",
        pinned: false,
        tags: ["공유", "축3", "BigQuery"],
        share: false,
      },
      {
        title: "토너먼트 — 생성 · 수락률",
        desc: "공유 격차의 100%가 수락률이고 발사는 1.22배 더 많다. 생성은 모바일만 붕괴.",
        url: "docs/tournament-share-rate.html",
        project: "sol",
        status: "진행중",
        version: "v9.0",
        updated: "2026-08-18 18:20",
        pinned: false,
        tags: ["토너먼트", "축3", "BigQuery"],
        share: false,
      },
      {
        title: "토너 초대 — 시도는 2배, 유입률은 절반",
        desc: "시도/DAU는 퍼블마의 2배인데 시도당 유입은 절반. 남은 가설은 친구 그래프 성숙도 하나.",
        url: "docs/invite-inflow-channel-maturity.html",
        project: "sol",
        status: "진행중",
        version: "v3.5",
        updated: "2026-08-19 09:54",
        pinned: false,
        tags: ["초대", "축3", "BigQuery"],
        share: false,
      },
      {
        title: "NRU 0~10분 — 6개 프로젝트 온보딩 비교",
        desc: "같은 정의로 재는 지표 4개에서 3승 1패. 값이 갈리는 이유는 가설 7건으로 분해했다.",
        url: "docs/nru-first-10min-compare.html",
        project: "multi",
        status: "진행중",
        version: "v4.2",
        updated: "2026-08-18 18:10",
        pinned: false,
        tags: ["온보딩", "축2", "BigQuery"],
        share: false,
      },
      {
        title: "5프로젝트 소셜 코드 대조표",
        desc: "공유 호출 · 지면 게이트 · 로그를 5개 프로젝트 코드로 나란히 놓은 28행 대조표.",
        url: "docs/social-code-matrix.html",
        project: "multi",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-19 08:55",
        pinned: false,
        tags: ["공유", "코드 실측", "정본"],
      },
      {
        title: "로딩 속도 — 3개 프로젝트 비교",
        desc: "부팅 지연 전량이 LOAD_FB→LOAD_INTRO 한 구간에 몰린다(코지의 3.3배).",
        url: "docs/loading-speed-compare.html",
        project: "multi",
        status: "완료",
        version: "v2.3",
        updated: "2026-08-18 18:10",
        pinned: false,
        tags: ["로딩", "축2", "정본"],
        share: false,
      },
      {
        title: "전면광고 지면 — 4개 프로젝트 플로우 비교",
        desc: "솔리테어 · 퍼블마 · 코지 · 마종의 전면광고를 유저 플로우 13개 노드에 올려 비교.",
        url: "docs/ad-placements.html",
        project: "multi",
        status: "완료",
        version: "v1.9",
        updated: "2026-08-14 09:57",
        pinned: false,
        tags: ["광고", "축1", "코드 실측"],
        share: false,
      },
      {
        title: "스토리 머지 — 역기획 구현 범위",
        desc: "목표는 Gossip Harbor 급. 레퍼런스 위키를 정본으로 시스템 20종을 세우고, 붙이기 전에 형태를 확정해야 하는 게이트 6개와 L0 보드 · L1 재화 · L2 진행까지 층을 갈랐습니다.",
        url: "docs/story-merge-kickoff-slim.html",
        project: "smg",
        status: "초안",
        version: "v5.1",
        updated: "2026-09-01 10:36",
        pinned: false,
        tags: ["머지", "인게임", "착수 범위"],
      },
      {
        title: "스토리 머지 — 리소스 예산",
        desc: "무엇이 무겁고 언제 불러오는가. 메모리는 파일이 아니라 해상도로 정해집니다 — 대화 애니 파일 7.3MB 가 메모리 90.8MB. 로딩 단위를 캐릭터가 아니라 감정(5.7MB)으로 잡아야 하는 이유를 솔리테어 실측으로 맞췄습니다.",
        url: "docs/story-merge-resource-budget.html",
        project: "smg",
        status: "추적",
        version: "v2.2",
        updated: "2026-09-01 15:54",
        pinned: false,
        tags: ["머지", "리소스", "실측 추적"],
      },
      {
        title: "머지 플로우 시뮬레이터",
        desc: "지금 코드가 각 단계에서 램을 얼마나 쓰는지 재는 페이지. 노드 11개·대사 37행을 그대로 태워 돌리고 단계별 MB 를 찍습니다 — 첫 대사에서 95MB, 예산의 158%. 고친 뒤 다시 열어 내려갔는지만 보면 됩니다.",
        url: "docs/merge-flow-sim.html",
        project: "smg",
        status: "초안",
        version: "v2.1",
        updated: "2026-09-01 15:31",
        pinned: false,
        tags: ["머지", "메모리 계측", "인터랙티브"],
      },
    ],
  },
  {
    id: "diagram",
    label: "다이어그램",
    accent: "balance",
    desc: "프로젝트별 전체 지면 플로우 맵 — 오픈맵 + 와이어프레임 캔버스",
    cards: [
      {
        title: "솔리테어 부팅 로그 플로우",
        desc: "앱이 켜지고 게임 시작 화면이 뜰 때까지 찍히는 로그를 실행 순서대로 세운 지도입니다. 구간마다 색을 고정해 어느 로그가 어느 구간을 재는지 색만 보고 갈리고, 2026-09-01 빌드 480 사고가 났던 1b 구간은 주황으로 따로 세웠습니다. 퍼널 게이트 9개 · 실패 분기 16개 · 공통 필드 6개를 파일·줄 번호까지 붙여 실측했습니다.",
        url: "docs/boot-log-flow.html",
        project: "sol",
        status: "완료",
        version: "v1.1",
        updated: "2026-09-02 12:11",
        pinned: false,
        tags: ["코드 실측", "로그 계측"],
      },
      {
        title: "솔리테어 전체 지면 플로우 맵",
        desc: "한 판의 라이프사이클을 세로 스파인으로 세운 오픈맵입니다. 부팅 → 로비 → 프리게임 → 인게임 → 결과 → 결과 후 7단계 → 로비 복귀가 위에서 아래로 한 줄기로 읽히고, 지면을 열면 프리팹 실측 화면 요소 1,575개로 그린 와이어프레임과 버튼별 흐름 · 컨텍스트 상태 기계 · FB 지면 15종이 나옵니다.",
        url: "docs/solitaire-flow-map.html",
        project: "sol",
        status: "완료",
        version: "v10.4",
        updated: "2026-08-28 10:24",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
      {
        title: "코인매치 전체 지면 플로우 맵",
        desc: "한 판의 진행을 세로 스파인으로 세운 오픈맵입니다. 부팅 → 진입 라우팅 → 로비 → 인게임 → 정산 → 판 종료 후 7단계가 위에서 아래로 한 줄기로 읽히고, 지면을 열면 세로 화면 와이어프레임 위에서 버튼을 눌러 호출 사슬을 그 자리에서 펼칩니다. 메소드·프리팹·버튼 이름으로 3,280항목을 검색해 그 지면의 상세까지 열어 줍니다.",
        url: "docs/coin-match-flow-map.html",
        project: "cmt",
        status: "완료",
        version: "v2.1",
        updated: "2026-08-28 15:00",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
      {
        title: "코지 전체 지면 플로우 맵",
        desc: "한 판의 진행을 세로 스파인으로 세운 오픈맵입니다. 로비가 껍데기고 탭 프리팹 5장이 실제 화면이라는 것, 판 종료 후 6단계가 위에서 아래로 한 줄기로 읽힙니다. 지면을 열면 프리팹 실측 화면 요소 1,449개로 그린 와이어프레임 위에서 버튼을 눌러 호출 사슬을 그 자리에서 펼칩니다.",
        url: "docs/cozytiles-flow-map.html",
        project: "coz",
        status: "완료",
        version: "v1.0",
        updated: "2026-08-28 16:40",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
      {
        title: "마종 전체 지면 플로우 맵",
        desc: "코지와 같은 판형으로 세운 오픈맵입니다. 마종은 로비에 탭이 없고 상점·도감·친구·토너먼트가 독립 View 4장이라는 점이 갈리는 지점입니다. 판 종료 후 5단계와 추천 매치가 다음 판의 컨텍스트를 정하는 구조를 폈습니다.",
        url: "docs/mahjong-flow-map.html",
        project: "mah",
        status: "완료",
        version: "v1.0",
        updated: "2026-08-28 16:40",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
      {
        title: "퍼블마 전체 지면 플로우 맵",
        desc: "이 게임만 부팅이 로비를 건너뛰고 판으로 직행합니다. 그래서 맵의 띠 순서도 인게임 → 판 종료 후 5단계 → 로비입니다. 전면광고 호출부가 3곳(마종 38·코지 27)인 대신 토너먼트 생성이 6곳으로 가장 많은 것도 이 구조에서 나옵니다.",
        url: "docs/block-blast-flow-map.html",
        project: "pbm",
        status: "완료",
        version: "v1.0",
        updated: "2026-08-28 17:10",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
      {
        title: "스토리머지 전체 지면 플로우 맵",
        desc: "맵을 세로로 세웠습니다. 가운데 줄기가 실제 재생 순서(켜짐 → 진입 → 노드 1~11 → 종료)이고 왼쪽은 읽는 것, 오른쪽은 여는 지면입니다. 노드 11개를 카드 안에 접지 않고 줄기 위에 펴서, 대사·태스크·삽화가 번갈아 나오는 진행이 한눈에 보입니다.",
        url: "docs/story-merge-flow-map.html",
        project: "smg",
        status: "완료",
        version: "v1.2",
        updated: "2026-08-28 09:11",
        pinned: false,
        tags: ["프리팹 실측", "인터랙티브"],
      },
    ],
  },
  {
    id: "validate",
    label: "검증",
    accent: "validate",
    desc: "수정 전/후 결과 대조",
    cards: [
      {
        title: "토너먼트 업데이트 KPI 검증 — 8/27 배포",
        desc: "P2P 오발송만 −29%, 공유·생성은 무변화. 클리어의 3.7%만 발사되고 병목은 유저 취소 93%.",
        url: "docs/tournament-update-kpi-0828.html",
        project: "sol",
        status: "완료",
        version: "v1.0",
        updated: "2026-08-28 12:21",
        pinned: false,
        tags: ["토너먼트", "BigQuery"],
      },
      {
        title: "전환 지면 중복 제거 — 바이럴 검증",
        desc: "조인 진입 판의 중복 지면을 없앤 8/20 배포. A/B 비교 — 포스트 +28.0%p · 피드 +20.4%p, 토너 공유·생성은 지면 1개분 도달률 감소.",
        url: "docs/switch-surface-dedupe-viral.html",
        project: "sol",
        status: "완료",
        version: "v2.4",
        updated: "2026-08-28 19:05",
        pinned: false,
        tags: ["컨텍스트", "BigQuery"],
      },
      {
        title: "토너먼트 공유 실패 — 수정 전/후",
        desc: "거절 두 원인의 전후 비교. 점수 없음은 8.3%→0.4%, 광고 충돌은 5.1%→4.0%.",
        url: "docs/tournament-share-fail-result.html",
        project: "sol",
        status: "완료",
        version: "v3.6",
        updated: "2026-08-20 10:47",
        pinned: false,
        tags: ["토너먼트", "공유", "BigQuery"],
        share: false,
      },
      {
        title: "토너먼트 생성 실패 복구 — 수정 전/후",
        desc: "문구 변형까지 되살리게 고친 결과. 못 살린 생성은 전후 모두 0, iOS 마침표 변형만 잡혔다.",
        url: "docs/tournament-create-recovery-result.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-20 09:19",
        pinned: false,
        tags: ["토너먼트", "BigQuery"],
        share: false,
      },
    ],
  },
  {
    id: "qa",
    label: "QA",
    accent: "plan",
    desc: "테스트 순서 · 케이스 · 이슈 트래커",
    cards: [
      {
        title: "QA 이슈 트래커",
        desc: "솔리테어 QA 채널 이슈 상시 목록. 줄을 펼치면 어떤 커밋으로 어떻게 고쳤는지 나온다.",
        url: "docs/qa-issue-code-audit.html",
        project: "sol",
        status: "Live",
        version: "v9.0",
        updated: "2026-08-19 10:07",
        pinned: true,
        tags: ["상시", "커밋 히스토리"],
        share: false,
      },
      {
        title: "토너먼트 참가 · 전환 다이얼로그 1회",
        desc: "전환 다이얼로그를 Play 1회로 줄이고 참가 불가 토너를 목록에서 뺀 수정의 QA 순서.",
        url: "docs/tournament-join-context-qa.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-13 18:40",
        pinned: false,
        tags: ["토너먼트", "컨텍스트"],
        share: false,
      },
      {
        title: "토너먼트 만들기 복구 · 솔로 전환 대기",
        desc: "끊긴 채 만들어진 토너를 성공 처리하고 솔로 대기를 30초→2초로 줄인 수정의 QA 순서.",
        url: "docs/tournament-create-recovery-qa.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-13 17:13",
        pinned: false,
        tags: ["토너먼트", "네트워크 오류"],
        share: false,
      },
      {
        title: "인게임 재도전",
        desc: "나가기 팝업 Retry 버튼 QA 순서 26케이스. v3.0에서 정산 시점과 복귀 지점이 바뀌었다.",
        url: "docs/ingame-retry-qa-flow.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-13 17:13",
        pinned: false,
        tags: ["정산", "광고"],
        share: false,
      },
      {
        title: "나가기 종료 처리 순서 변경",
        desc: "종료 알림을 전면광고보다 먼저 보내도록 바꾼 수정의 QA 순서. 광고 중 앱 종료가 핵심.",
        url: "docs/quit-gameend-order-qa.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-13 17:13",
        pinned: false,
        tags: ["광고"],
        share: false,
      },
      {
        title: "SPEC-038 토너 초대 토글",
        desc: "토너 판을 깰 때 공유와 초대가 번갈아 뜨는 기능의 QA 순서. 안 뜨는 게 정상인 경우 포함.",
        url: "docs/spec-038-qa-flow.html",
        project: "sol",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-13 17:13",
        pinned: false,
        tags: ["초대", "토너먼트"],
        share: false,
      },
    ],
  },
  {
    id: "deploy",
    label: "도구 · 배포",
    accent: "deploy",
    desc: "작업 기록 · 이식 가이드 · 사내 툴",
    cards: [
      {
        title: "데코 영역 아트 리소스 트리 — 이전 프로젝트 사례",
        desc: "이전 네이티브 프로젝트에서 데코 영역 아트 리소스를 어떤 트리로 공유받았는지. 이유는 상태별 대응 — 망가짐→고쳐짐 · 5단 성장 · 완성 3종 택1이 같은 형태로 흡수된다.",
        url: "docs/deco-area-prefab-structure.html",
        project: "smg",
        status: "초안",
        version: "v3.5",
        updated: "2026-08-24 14:00",
        pinned: false,
        tags: ["아트", "데코", "임시"],
      },
      {
        title: "머지 웹 프로젝트 — 아트 인계 · 이미지 관리",
        desc: "아트 인계 규격 + 부팅 예산 상한 4축(전송 1.5MB / 파싱 2.0MB / 디코드 3Mpx / bpp 2.0). 웹 빌드 2종 부팅 페이로드 실측. 오픈맵·단편형 2안은 타사 머지 FB IG 실측.",
        url: "docs/art-resource-handoff.html",
        project: "smg",
        status: "진행중",
        version: "v6.0",
        updated: "2026-08-24 14:00",
        pinned: false,
        tags: ["아트", "정본"],
        share: false,
      },
      {
        title: "스토리머지 커밋 히스토리 — 왜 이렇게 고쳤나",
        desc: "커밋 문구로 훑고 필요한 것만 펼치는 목록. 틀만 세워 둔 상태 — 수록 0건, 첫 커밋부터 채운다.",
        url: "docs/commit-history-story-merge.html",
        project: "smg",
        status: "초안",
        version: "v0.1",
        updated: "2026-08-31 17:49",
        pinned: false,
        tags: ["커밋 히스토리", "상시"],
      },
      {
        title: "코인매치 커밋 히스토리 — 왜 이렇게 고쳤나",
        desc: "커밋 문구로 훑고 필요한 것만 펼치는 목록. 06-02~08-28 커밋 47건 · 작성자 6명 · 영역·작성자 두 축 필터.",
        url: "docs/commit-history-coin-match.html",
        project: "cmt",
        status: "진행중",
        version: "v2.0",
        updated: "2026-08-28 21:10",
        pinned: false,
        tags: ["커밋 히스토리", "상시"],
      },
      {
        title: "솔리테어 커밋 히스토리 — 왜 이렇게 고쳤나",
        desc: "커밋 문구로 훑고 필요한 것만 펼치는 목록. 07-13~08-27 Max 커밋 173건 diff 전량 실측.",
        url: "docs/commit-history-solitaire.html",
        project: "sol",
        status: "진행중",
        version: "v11.0",
        updated: "2026-08-28 18:40",
        pinned: false,
        tags: ["커밋 히스토리", "상시"],
      },
      {
        title: "토너먼트 생성 복구 판정 정규화 — 다른 프로젝트 이식",
        desc: "이식할 것은 에러 문구 끝 마침표를 떼는 것 하나. 4개 프로젝트 11곳의 현재 상태 · 조치.",
        url: "docs/tournament-recovery-message-port.html",
        project: "multi",
        status: "완료",
        version: "v3.5",
        updated: "2026-08-20 10:05",
        pinned: false,
        tags: ["토너먼트", "이식"],
        share: false,
      },
    ],
  },
];
